name: Build and Publish Docker Image

on:
  push:
    branches:
      - feature

env:
  IMAGE_NAME: backend

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./internal
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
