name: Deploy to Server

on: workflow_dispatch



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH }}
          passphrase: ${{ secrets.PASS }}
          script: |
            cd /home/kuehler
            docker compose pull
            docker compose up -d