name: Deploy to Server

on:
  push:
    branches:
      - feature

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into the server
        uses: appleboy/ssh-action@master
        with:
          host: your-server-ip
          username: ${{ secrets.USER}}
          key: ${{ secrets.SSH }}
          passphrase: ${{ secrets.PASS }}

      - name: Deploy with Docker Compose
        run: |
          cd /path/to/your/app
          docker-compose pull
          docker-compose up -d